### ISSUE TITLE
Deploy active learning demo env

### ISSUE THREAD

**Issue by peterdudfield** [materiom/ActiveLearningAPI#11]
Deploy the active learning api, ready to be tested with front end

There is a docker file ready to go in the Repo, 
This should be build and pushed to dockerhub #2, and then loaded somewhere for deployement

**Comment by liamreeves** [comment]
I am trying to find a good place to host a test api

**Comment by liamreeves** [comment]
I can self host but CORS is so annoying to get around

**Comment by peterdudfield** [comment]
> I can self host but CORS is so annoying to get around

ive put this code in https://github.com/materiom/active-learning-api/blob/main/src/main.py#L35, so I think it'll work from any address.

**Comment by peterdudfield** [comment]
> I am trying to find a good place to host a test api

Can always put it on an ec2 mahcine in AWS?

**Comment by liamreeves** [comment]
It's been deployed to google cloud :)

**Comment by peterdudfield** [comment]
Cool - @liamreeves can you share the link?
